"""Evaluation and reporting utilities."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    brier_score_loss,
    precision_recall_curve,
    recall_score,
    roc_auc_score,
    roc_curve,
)


def recall_at_capacity(y: np.ndarray, score: np.ndarray, capacity: float) -> tuple[float, float]:
    cutoff = np.quantile(score, 1.0 - capacity)
    pred = score >= cutoff
    return float(recall_score(y, pred)), float(cutoff)


def evaluate(test: pd.DataFrame, scored: pd.DataFrame, exclusion_score: np.ndarray,
             review_capacity: float) -> dict[str, float]:
    y = test["fraud"].to_numpy()
    novel = test["novel_fraud"].to_numpy().astype(bool)
    risk = scored["risk"].to_numpy()
    recall_cap, cutoff = recall_at_capacity(y, risk, review_capacity)
    pred_review = risk >= cutoff
    metrics = {
        "n_test": int(len(test)),
        "fraud_rate": float(y.mean()),
        "roc_auc": float(roc_auc_score(y, risk)),
        "average_precision": float(average_precision_score(y, risk)),
        "brier": float(brier_score_loss(y, risk)),
        "recall_at_capacity": recall_cap,
        "review_capacity": float(pred_review.mean()),
        "false_alert_rate": float(pred_review[y == 0].mean()),
        "novel_fraud_recall": float(recall_score(y[novel], pred_review[novel])) if novel.any() else 0.0,
        "exclusion_roc_auc": float(roc_auc_score(test["exclusion"], exclusion_score)),
    }
    return metrics


def save_figures(test: pd.DataFrame, scored: pd.DataFrame, exclusion_score: np.ndarray, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    y = test["fraud"].to_numpy()
    risk = scored["risk"].to_numpy()

    fig, axes = plt.subplots(1, 2, figsize=(10, 4.2))
    fpr, tpr, _ = roc_curve(y, risk)
    axes[0].plot(fpr, tpr, color="#0b5fff", linewidth=2)
    axes[0].plot([0, 1], [0, 1], "--", color="#9aa4b2")
    axes[0].set(xlabel="False positive rate", ylabel="True positive rate", title="Fraud-risk ROC")
    axes[0].grid(alpha=.25)
    precision, recall, _ = precision_recall_curve(y, risk)
    axes[1].plot(recall, precision, color="#7a3ef0", linewidth=2)
    axes[1].set(xlabel="Recall", ylabel="Precision", title="Fraud-risk precision-recall")
    axes[1].grid(alpha=.25)
    fig.tight_layout()
    fig.savefig(out / "fraud_curves.pdf", bbox_inches="tight")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    plot = pd.DataFrame({"channel": test["channel"], "score": exclusion_score, "excluded": test["exclusion"]})
    groups = [plot.loc[(plot.channel == c) & (plot.excluded == 1), "score"] for c in sorted(plot.channel.unique())]
    ax.boxplot(groups, tick_labels=sorted(plot.channel.unique()), showfliers=False)
    ax.set(title="Exclusion-risk score for affected legitimate journeys", ylabel="Exclusion anomaly score")
    ax.grid(axis="y", alpha=.25)
    fig.tight_layout()
    fig.savefig(out / "exclusion_by_channel.pdf", bbox_inches="tight")
    plt.close(fig)


def write_results(metrics: dict[str, float], out_json: Path, out_tex: Path) -> None:
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    lines = [
        "% Generated by scripts/run_experiment.py; do not edit by hand.",
        f"\\newcommand{{\\TestN}}{{{metrics['n_test']:,}}}",
        f"\\newcommand{{\\FraudRate}}{{{100*metrics['fraud_rate']:.2f}\\%}}",
        f"\\newcommand{{\\RocAuc}}{{{metrics['roc_auc']:.3f}}}",
        f"\\newcommand{{\\AvgPrecision}}{{{metrics['average_precision']:.3f}}}",
        f"\\newcommand{{\\Brier}}{{{metrics['brier']:.4f}}}",
        f"\\newcommand{{\\RecallCapacity}}{{{100*metrics['recall_at_capacity']:.1f}\\%}}",
        f"\\newcommand{{\\ReviewCapacity}}{{{100*metrics['review_capacity']:.1f}\\%}}",
        f"\\newcommand{{\\NovelRecall}}{{{100*metrics['novel_fraud_recall']:.1f}\\%}}",
        f"\\newcommand{{\\ExclusionAuc}}{{{metrics['exclusion_roc_auc']:.3f}}}",
    ]
    out_tex.write_text("\n".join(lines) + "\n", encoding="utf-8")

